ue:
  supi: "imsi-2089300007487"
  ranuengapid: 1
  amfuengapid: 1
  ipudpconnection : "192.168.1.103"
  portudpconnection : "500"

n3iwfinfo:
  ikebindaddress: "146.190.119.235"
  ikebindport: "500"
  ipsecifaceprotocol: "udp"

logs:
  level: 4