ue:
  authsubscription:
    permanentkeyvalue: "5122250214c33e723a5dd523fc145fc0"
    opcvalue: "981d464c7c52eb6e5036234984ad0bcf"
    opvalue: "c9e8763286b5b9ffbdf56e1297d0887b"
    sequencenumber: "16f3b3f70fcf"
  supi: "imsi-2089300007487"
  ranuengapid: 1
  amfuengapid: 1
  authenticationmanagementfield : "8000"
  localpublicipaddr : "134.122.116.111"
  localpublicportudpconnection : "500"
  linkgre:
    name : "gretun0"
    ipaddress: [60,60,0,1]
    mask: [255,255,255,0]
  ipsecinterfacename : "ipsec0"
  ipsecinterfacemark: "5" # IPSec virtual interface mark (Any value except to 0, default value is 7 if not defined)
  snssai: # Single Network Slice Selection Assistance Information
    sst: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
    sd: "010203" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                     
n3iwfinfo:
  ikebindaddress: "146.190.144.213" # IP address of Nwu interface (IKE) on N3IWF
  ikebindport: "500"
  ipsecifaceprotocol: "udp"

upfinfo:
  networkaddress: [146, 190, 144, 0] # Network address where the UPF is located (route command). It will be used to build the access route via GRE tunnel
  networkmask: [255, 255, 240, 0] # Network mask where the UPF is located (route command). It will be used to build the access route via GRE tunnel

logs:
  level: 4
