ue:
  supi: "imsi-2089300007487"
  ranuengapid: 1
  amfuengapid: 1
  ipudpconnection : "143.110.151.149"
  portudpconnection : "500"

n3iwfinfo:
  ikebindaddress: "144.126.213.51"
  ikebindport: "500"
  ipsecifaceprotocol: "udp"

logs:
  level: 4