ue:
  supi: "imsi-2089300007487"
  ranuengapid: 1
  amfuengapid: 1
  authenticationmanagementfield : "8000"

n3iwfinfo:
  ipsecifaceaddr: "10.43.0.230"
  ipsecifaceport: "31500"
  ipsecifaceprotocol: "udp"

logs:
  level: 4