ue:
  authsubscription:
    permanentkeyvalue: "5122250214c33e723a5dd523fc145fc0"
    opcvalue: "981d464c7c52eb6e5036234984ad0bcf"
    opvalue: "c9e8763286b5b9ffbdf56e1297d0887b"
    sequencenumber: "16f3b3f70fc1"
  msin: "0000000001"
  hplmn:
    mcc: "208"
    mnc: "93"
  ranuengapid: 1
  amfuengapid: 1
  authenticationmanagementfield : "8000"
  localpublicipaddr : "192.168.122.1"
  localpublicportudpconnection : "500"
  linkgre:
    name : "gretun"
  ipsecinterfacename : "ipsec0" # IP address of IPSec virtual interface (IPsec tunnel enpoint to N3IWF)
  ipsecinterfacemark: 5 # IPSec virtual interface mark (Any value except to 0, default value is 7 if not defined)
  snssai: # Single Network Slice Selection Assistance Information
    sst: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
    sd: "010203" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  pdusessionid: 1
  dnnstring: "internet"

n3iwfinfo:
  ikebindaddress: "192.168.122.116" # IP address of Nwu interface (IKE) on N3IWF
  ikebindport: "500"
  ipsecifaceprotocol: "udp"

metricinfo:
  httpaddress: "127.0.0.1"
  httport: "5001"

# how detailed to output, value: trace, debug, info, warn, error, fatal, panic
logs:
  level: info
