ue:
  supi: "imsi-2089300007487"
  ranuengapid: 1
  amfuengapid: 1
  authenticationmanagementfield : "8000"

n3iwfinfo:
  ipsecifaceaddr: "192.168.127.1"
  ipsecifaceport: "500"
  ipsecifaceprotocol: "udp"

logs:
  level: 4